### ISSUE TITLE
No more data is displayed

### ISSUE THREAD

**Issue by JVF2** [rseidt/MMM-bringList#4]
Hello,

unfortunately no more data is displayed.
I have not made any changes and the rest of the MagicMirrors works fine.

Thank you very much in advance.

**Comment by BassXX** [comment]
The same for me! Changed nothing in the config.js.

Nothing displayed anymore...Bring updated its APP on August, 2nd. Maybe the made some changes?

**Comment by Jagsi1981** [comment]
Same here....

**Comment by quark777** [comment]
same for me

**Comment by AJET69** [comment]
New install with the same effect, Except I never saw it work. I see the header in MM but that is all.
Here is what I see in the console:
[02.09.2021 21:43.57.524] [LOG]   BRING: Received registration notification.
[02.09.2021 21:43.57.529] [LOG]   BRING: Loop not running. Starting.
[02.09.2021 21:43.57.531] [LOG]   BRING: Starting List update...
[02.09.2021 21:43.57.652] [INFO]  Checking git for module: MMM-bringList
[02.09.2021 21:43.58.276] [INFO]  Newsfeed-Fetcher: Broadcasting 56 items.
[02.09.2021 21:43.58.544] [INFO]  Calendar-Fetcher: Broadcasting 6 events.
[02.09.2021 21:43.59.393] [LOG]   BRING: List content has changed since last interval. Refreshing view.
[02.09.2021 21:44.00.028] [ERROR] Whoops! There was an uncaught exception...
[02.09.2021 21:44.00.053] [ERROR] TypeError: Cannot read property 'forEach' of undefined
    at BringProfile.setImageToItem (/home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:274:35)
    at BringProfile.setIconUrl (/home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:266:14)
    at /home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:227:27
    at Array.forEach (<anonymous>)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:220:28)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-bringList/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-bringList/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-bringList/node_modules/request/request.js:1083:12)
[02.09.2021 21:44.00.058] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[02.09.2021 21:44.00.060] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[02.09.2021 21:44.20.967] [LOG]   Shutting down server...
[02.09.2021 21:44.20.968] [LOG]   Stopping module helper: updatenotification
[02.09.2021 21:44.20.969] [LOG]   Stopping module helper: calendar
[02.09.2021 21:44.20.969] [LOG]   Stopping module helper: newsfeed
[02.09.2021 21:44.20.971] [LOG]   BRING: Loop running. Stopping.

**Comment by daniel-san-fried** [comment]
The other module from user "werthdavid" doesn't work aswell so this is a bring-related issue

**Comment by winscripting** [comment]
Hey, I wrote a pull request which fixed the problem for me :-)
